### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by testpuddle** [DepartureLabsIC/quark-docs#1]
Same issue needs to be updated in this document to reflect the new URL.

From
domain: "https://ebgyc-nqaaa-aaaaf-qad6q-cai.ic0.app/",

To:
domain: "https://pwwjo-6qaaa-aaaam-aadka-cai.ic0.app/",

**Comment by danielterwiel** [comment]
Thanks for mentioning this. Please refer to our updated documentation: https://departurelabs.notion.site/Quark-Testnet-30980b5dd38b448eba25cd8aa6d20bb3
